name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test_ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test SSH Connection
      env:
        HOST_NAME: ${{ secrets.SERVER_HOST_NAME }}
        KEY_NAME: ${{ secrets.SERVER_KEY_NAME }}
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
      run: |
        # Create the .ssh directory
        mkdir -p ~/.ssh
        # Write the SSH private key to the file
        echo "$KEY_NAME" > ~/.ssh/id_rsa
        # Set permissions for the key file
        chmod 600 ~/.ssh/id_rsa
        # Test the SSH connection
        ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $HOST_NAME@$IP_ADDRESS 'echo "Connected successfully"'
