name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python 3.10 environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Archive repository
      run: |
        git archive -o repo.tar.gz HEAD

    - name: Deploy to VM
      env:
        HOST_NAME: ${{ secrets.SERVER_HOST_NAME }}
        KEY_NAME: ${{ secrets.SERVER_KEY_NAME }}
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
      run: |
        echo "Connecting to VM"
        scp -o StrictHostKeyChecking=no -i $KEY_NAME repo.tar.gz $HOST_NAME@$IP_ADDRESS:/home/azureuser

        ssh -o StrictHostKeyChecking=no -i $KEY_NAME $HOST_NAME@$IP_ADDRESS << 'EOF'
          echo "Extracting repository on VM"
          cd /home/azureuser
          tar -xzf repo.tar.gz

          echo "Creating a virtual environment"
          python -m venv myenv
          source myenv/bin/activate

          echo "Running the application"
          python app.py
        EOF
