name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python 3.10 environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Archive repository
      run: |
        git archive -o repo.tar.gz HEAD

    - name: Deploy to VM
      env:
        HOST_NAME: ${{ secrets.SERVER_HOST_NAME }}
        KEY_NAME: ${{ secrets.SERVER_KEY_NAME }}
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
      run: |
        echo "Connecting to VM"
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $KEY_NAME repo.tar.gz $HOST_NAME@$IP_ADDRESS:/home/azureuser
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $KEY_NAME $HOST_NAME@$IP_ADDRESS << 'EOF'
          set -e
          echo "Extracting repository on VM"
          cd /home/azureuser
          tar -xzf repo.tar.gz
          echo "Creating a virtual environment"
          VENV_DIR="myenv"
          python -m venv $VENV_DIR
          source $VENV_DIR/bin/activate
          
          if [ -f app.py ]; then
            echo "Running the application"
            python app.py
          else
            echo "app.py not found!"
            exit 1
          fi

          # Clean up
          rm repo.tar.gz
        EOF
